changelog:
  exclude:
    authors:
      # Ignore the release PR created by github-actions
      - github-actions
    labels:
      - ignore-for-release
      - pr(chore)
  categories:
    - title: Breaking Changes 🍭
      labels:
        - "change: breaking"
    - title: New Features 🎉
      labels:
        - "change: feat"
    - title: Performance 🚀
      labels:
        - "change: perf"
    - title: Bug Fixes 🐞
      labels:
        - "change: fix"
    - title: Document 📖
      labels:
        - "change: docs"
    - title: Other Changes
      labels:
        - "*"
